### ISSUE TITLE
Fresh install fails - Dependencies issues

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/calibreweb_ynh#36]
I've just tried to do a fresh install of calibreweb on Armbian Stretch, it failed and here is the log:
https://paste.yunohost.org/raw/xoxoxiyaye
I saw it asked for libxml2, I'll try to install it first and then retry installing calibreweb

**Comment by roukydesbois** [comment]
Hum, it's actually installed already:
```
libxml2 is already the newest version (2.9.4+dfsg1-2.2+deb9u2).
libxml2 set to manually installed.
```

**Comment by roukydesbois** [comment]
But libxml2-dev is not installed, and it looks it's required from the logs I shared above:

> 2020-05-10 08:49:11,530: WARNING -   ** make sure the development packages of libxml2 and libxslt are installed **

**Comment by Krakinou** [comment]
Hi,
This is strange as on all the tests machines I have, none of these package are installed nor required?

Could you tell me which python version and package are installed on Armbian?
```
python3 -V
dpkg-query -W libxml*
dpkg-query -W libxslt*
```
I'll try to set up a VM with armbian to check it for further release. Can you guide me to which image I should download?

Anyhow, I think that installing libxml2-dev should solve the issue:
```
apt install libxml2-dev
```

**Comment by roukydesbois** [comment]
Unfortunately I have already installed the dev libraries (that were not installed), so this is the current situation:

```
admin@ynh:~$ python3 -V
Python 3.5.3
admin@ynh:~$ dpkg-query -W libxml*
libxml-parser-lite-tree-perl	
libxml-parser-perl	
libxml-sax-perl	
libxml2:armhf	2.9.4+dfsg1-2.2+deb9u2
libxml2-dev:armhf	2.9.4+dfsg1-2.2+deb9u2
libxmlsec1	1.2.23-0.1
libxmlsec1-openssl	1.2.23-0.1
libxmltooling6	
admin@ynh:~$ dpkg-query -W libxslt*
libxslt-dev	
libxslt1-dev:armhf	1.1.29-2.1+deb9u2
libxslt1.1:armhf	1.1.29-2.1+deb9u2
```
And the install still fails:
https://paste.yunohost.org/raw/egopopivah

My armbian details:
```
Armbian 20.02.1 Stretch
Welcome to Armbian stretch with Linux 5.4.35-sunxi
```

**Comment by Krakinou** [comment]
Could you try to install the testing? 
I tried changing the lxml install from pip to the prebuilt python3-lxml package
```yunohost app install https://github.com/YunoHost-Apps/calibreweb_ynh/tree/Testing```

**Comment by roukydesbois** [comment]
Installing the Testing branch worked!

**Comment by Krakinou** [comment]
Closed with #37
